### ISSUE TITLE
Add pause between integration tests

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1598]
The kubeAPI has been erroring for a while. We have a theory that this is caused by the integration tests spamming the API every hour. To test this we paused the integration test pipeline for a whole day and observed the API was performing as expected without errors. 

To stop the integration tests from spamming the API we have decided to add a delay between each test.

**Comment by jasonBirchall** [comment]
We're seeing the following error in the kubeAPI logs:
```
W0121 10:16:42.343922       1 request.go:155] Auditing failed of  request: encoding failed: /, Kind= is unstructured and is not suitable for converting to "monitoring.coreos.com/v1"
```

Each CRD is reporting the same error and occurring around once per hour.

**Comment by jasonBirchall** [comment]
This is the error from Prometheus:
```
[FIRING:1] :warning: KubeAPILatencyHigh
Alert: The API server has a 99th percentile latency of 1.99 seconds for POST ingresses.
     Details:
      - alertname: KubeAPILatencyHigh
      - endpoint: https
      - job: apiserver
```
