### ISSUE TITLE
Setup monitoring/prometheus-operator-kube-proxy metrics

### ISSUE THREAD

**Issue by vijay-veeranki-moj** [ministryofjustice/cloud-platform#1636]
With the promethus-operator upgrade to 8.7.0, we now have a option to get option to scrape kube-proxy. But as it is available in kube-system, we are not able to get the metrics and getting the below error

```https://prometheus.cloud-platform.service.justice.gov.uk/targets#job-monitoring%2fprometheus-operator-kube-proxy%2f0```

Investigate options to get it working. 

https://github.com/helm/charts/issues/16476
https://github.com/kubernetes/kops/issues/6472#issuecomment-551847615

From the values file.

```
## Component scraping kube proxy
##
kubeProxy:
  enabled: true

  ## If your kube proxy is not deployed as a pod, specify IPs it can be found on
  ##
  endpoints: []
  # - 10.141.4.22
  # - 10.141.4.23
  # - 10.141.4.24

  service:
    port: 10249
    targetPort: 10249
    # selector:
    #   k8s-app: kube-proxy

  serviceMonitor:
    ## Scrape interval. If not set, the Prometheus default scrape interval is used.
    ##
    interval: ""
```
