### ISSUE TITLE
Find a way to revoke users' cluster credentials when they leave

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform#1681]
Currently, when users authenticate to the cluster, they get a token which
grants them access to the cluster for 30 days. Hypothetically, if a developer
left with bad feelings the day after they got their token, they could do
malicious things with it for the next 30 days.

**We have no way to revoke users' credentials before they are due to expire.**

We need a strategy for how to do this. One option is to implement some kind of
certificate revocation list (CRL). At a minimum, this would involve something
like this:

* Alter the kubernetes API server so that every inbound call looked at the
presented certificate and checked to see if it was on the CRL (probably by
computing an identifying hash, and then checking to see if that hash is on the
list). The list would, ideally, be stored in etcd.

* Add a new API call "revoke certificate" which takes the certificate
identifier and adds it to the CRL (with suitable checks to ensure that this
only happens if the caller has appropriate permissions - we don't want users to
be able to revoke each others certificates)

* Alter kuberos so that, whenever a certificate is issued, we have a record of
its identifier, expiration date and the user to whom it was issued (so that we
know which certificates to revoke when someone leaves)

* Have a process which prunes the CRL, removing expired certificates, so that
it doesn't grow indefinitely.

The links below include links to PRs to implement some of these functions.

NB: This could also be done in a user-centric rather than certificate-centric
way. i.e. we check a "Revoked users list" rather than a "Revoked certificates
list"

See also:

https://github.com/kubernetes/kubernetes/issues/60917
https://github.com/kubernetes/kubernetes/issues/18982
https://github.com/kubernetes/kubernetes/pull/35698

**Comment by digitalronin** [comment]
Interesting writeup of k8s authentication options:
https://www.magalix.com/blog/kubernetes-authentication

In particular, it looks like we should be able to use the `--authentication-token-webhook-config-file` parameter to get the api server to check credentials with github, every so often.

**Comment by digitalronin** [comment]
Next step, try using a deployment, instead of a daemonset, running as a non-root user, and hitting it via an https ingress.

**Comment by digitalronin** [comment]
The app. is running, but I don't see any log output when I hit the kubernetes API, and I'm not sure how to proceed.

**Comment by digitalronin** [comment]
I can see in the kube-apiserver pod logs that I get this error with a bad token

```
kube-apiserver-ip-172-20-110-67.eu-west-2.compute.internal kube-apiserver E0312 14:38:28.417276       1 webhook.go:107] Failed to make webhook authenticator request: the server has asked for the client to provide credentials
kube-apiserver-ip-172-20-110-67.eu-west-2.compute.internal kube-apiserver E0312 14:38:28.417328       1 authentication.go:65] Unable to authenticate the request due to an error: [invalid bearer token, oidc: verify token: oidc: malformed jwt: illegal base64 data at input byte 120, the server has asked for the client to provide credentials]
```

The relevant source code seems to be this [webhook.go](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook/webhook.go)

**Comment by digitalronin** [comment]
I'm stuck here, so I'm putting this ticket on hold. Here are some snippets that might be useful:

Add to kops spec:
```
  fileAssets:
  - content: |
      kind: Config
      apiVersion: v1
      preferences: {}
      clusters:
      - name: github-authn
        cluster:
          server: https://github-authn.apps.david-auth.cloud-platform.service.justice.gov.uk/authenticate
      users:
      - name: authn-apiserver
        user:
          token: secret
      contexts:
      - name: webhook
        context:
          cluster: github-authn
          user: authn-apiserver
      current-context: webhook
    name: token-webhook-config.yaml
    path: /srv/kubernetes/token-webhook-config.yaml
    roles:
    - Master
```

My fork of the github-authn repo (which runs as a non-root user):
https://github.com/digitalronin/kubernetes-github-authn

One option to consider, when we pick this ticket up again, is a completely change our approach to authenticating to the cluster.

It is possible to set up kubernetes to use a text file containing a list of allowed tokens. If it is possible a) for this file to contain github personal access tokens, and b) to automate adding/removing users and their tokens, then this could be a better approach than the one we're using now, since it allows us to quickly revoke tokens when users leave and/or tokens are leaked.
It's something to think about, anyway, if we can't get webhook token auth working properly.

As a next step, I would suggest trying to set up a test cluster using the auth. mechanism described in this article:  
https://www.shogan.co.uk/kubernetes/custom-kubernetes-webhook-token-authentication-with-github-a-nodejs-implementation/
