### ISSUE TITLE
Investigate the high KubeAPILatencyHigh alarms

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#1717]
This alarm will be silenced as it is clogging up the low-priority channel.

```
[FIRING:1] :warning: KubeAPILatencyHigh
Alert: The API server has an abnormal latency of 1.2663306509999759 seconds for POST ingresses.
     Details:
      - alertname: KubeAPILatencyHigh
      - clusterName: live-1
      - component: apiserver
      - endpoint: https
      - group: extensions
      - job: apiserver
      - namespace: default
      - prometheus: monitoring/prometheus-operator-prometheus
      - resource: ingresses
      - scope: namespace
      - service: kubernetes
      - severity: warning
      - verb: POST
      - version: v1beta1

     -----
```
