### ISSUE TITLE
OPA Policy to restrict the hostnames that an ingress can use in test cluster

### ISSUE THREAD

**Issue by vijay-veeranki-moj** [ministryofjustice/cloud-platform#1743]
## Background

The ingress definition has a "live-1" domain name, and cert-manager in the
test cluster will not be able to make the change it wants to make to the
route53 API. This causes it to spam AWS, resulting in our account getting
throttled because we exceed the 5 requests/second limit for our account.

Create an OPA Policy to restrict the hostnames that an ingress can use in test cluster.

## Approach

Our existing OPA admissionController: ValidatingWebhookConfiguration , already set up with Ingress resource, that are subject to OPA policy checks. So no extra admissionControllerRules needed for the policy.

```
admissionControllerRules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["extensions"]
    apiVersions: ["*"]
    resources: ["ingresses"]
```

-> Write a OPA policy that restricts the hostnames that an ingress can use in test cluster

https://www.openpolicyagent.org/docs/latest/kubernetes-tutorial/#4-define-a-policy-and-load-it-into-opa-via-kubernetes

OPA Policy

```
package cloud_platform.admission

import data.kubernetes.ingresses

operations = {"CREATE", "UPDATE"}

deny[msg] {
  input.request.kind.kind == "Ingress"
  operations[input.request.operation]
  host := input.request.object.spec.rules[_].host
  not fqdn_matches_any(host, valid_ingress_hosts)
  msg := sprintf("invalid ingress host %q", [host])
}

valid_ingress_hosts = {host |
  whitelist := "*.vj-wh-dns.cloud-platform.service.justice.gov.uk"
  hosts := split(whitelist, ",")
  host := hosts[_]
}

fqdn_matches_any(str, patterns) {
  fqdn_matches(str, patterns[_])
}

fqdn_matches(str, pattern) {
  pattern_parts := split(pattern, ".")
  pattern_parts[0] == "*"
  str_parts := split(str, ".")
  n_pattern_parts := count(pattern_parts)
  n_str_parts := count(str_parts)
  suffix := trim(pattern, "*.")
  endswith(str, suffix)
}

fqdn_matches(str, pattern) {
    not contains(pattern, "*")
    str == pattern
}
```

-> Apply OPA policy created, with a condition to  apply only on test cluster
In [opa.tf](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/master/terraform/cloud-platform-components/opa.tf)

```
resource "kubernetes_config_map" "ingress_accepted" {
  count      = var.enable_ecr_exporter ? 1 : 0
  metadata {
    name      = "ingress-accepted"
    namespace = helm_release.open-policy-agent.namespace

    labels = {
      "openpolicyagent.org/policy" = "rego"
    }
  }

  data = {
    main = file(
      "${path.module}/resources/opa/policies/ingress-whitelist.rego",
    )
  }

  lifecycle {
    ignore_changes = [metadata.0.annotations]
  }
}
```

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

Use the Policy in the Approach above and update the policy to pick the `valid_ingress_hosts.whitelist` domain name from default cert in ingress-controller or annotation/label of a namespace which contain domain name of a test cluster, 

ku -n ingress-controllers get certificates default -o yaml

```
spec:
  acme:
    config:
    - dns01:
        provider: route53-cloud-platform
      domains:
      - '*.apps.vj-wh-dns.cloud-platform.service.justice.gov.uk'
  commonName: '*.apps.vj-wh-dns.cloud-platform.service.justice.gov.uk'
  dnsNames:
  - '*.apps.vj-wh-dns.cloud-platform.service.justice.gov.uk'
```

## Definition of done

- [ ] OPA Policy Created
- [ ] Rego Tests created for the OPA Policy
- [ ] Test it in test cluster
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
