### ISSUE TITLE
Run Checkov on cloud-platform terraform modules.

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#2033]
This is related to https://github.com/ministryofjustice/cloud-platform/issues/1978

Run Checkov on cloud-platform terraform modules to detect security and compliance misconfigurations.

Team decided to start using Checkov with cloud-platform terraform modules. We can start simple with one of our module like s3 or rds as a GitHub action.
https://www.checkov.io/4.Integrations/github-actions.html

```
---
name: Checkov
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python $
        uses: actions/setup-python@v1
        with:
          python-version: $
      - name: Test with Checkov
        run: |
          pip install checkov
          checkov -d .
```

We may not want this to cover all the checks form the default policies, to avoid that we need to maintain Suppressing/Ignoring.

If you’d like to allowlist or denylist a check_id from being executed, use the --check(allowlist) or --skip-check flags.

If we are happy with the results we can extent Checkov usage to all our modules and also our infrastructure repo modules.
