### ISSUE TITLE
Create 'cloud-platform' cli for ECR 

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#2060]
## Background

Create a cli command which will generate terraform file for creating ECR using [ECR terraform module](https://github.com/ministryofjustice/cloud-platform-terraform-ecr-credentials) inside end users namespace directory in [environment repo](https://github.com/ministryofjustice/cloud-platform-environments). 

It can be `cloud-platform environment ecr create`

## Approach

Add cli command to [this repo](https://github.com/ministryofjustice/cloud-platform-moj-cp) 

Add tests to verify the cli command

## Questions

Can the ecr repo name be auto generated using the existing values when creating the namespace?

## Definition of done

- [ ] cli created and tested
- [ ] readme has been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
If users channel information is available as part of cloud-platform-cli, Using cloud-platform-cli to create ECR can also set prometheus alert in the user's namespace by default when user create a ECR repository.

```
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-custom-alerts-ecr-exporter
  namespace: monitoring
  labels:
    prometheus: prometheus-operator
    role: alert-rules
spec:
  groups:
  - name: ecr-monitoring
    rules:
    - alert: ECR-Imagecount_Amber-Alert
      expr: aws_ecr_repository_image_count > 500
      for: 10m
      labels:
        severity: <user-channel>
      annotations:
        message: Image count for the Repository {{ $labels.repository_name }} is more than 500.
        runbook_url: https://docs.aws.amazon.com/AmazonECR/latest/userguide/service_limits.html
```
