### ISSUE TITLE
Update user guide for users to set up ECR Alerts 

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#2114]
## Background

Teams Image count for the ECR repository alerts routed to low-priority-alerts and it is causing to ignore other alerts. There is a [ticket](https://github.com/ministryofjustice/cloud-platform/issues/2112) to remove the ECR alerts. This issue is to create a user-guide for users to use the ECR metrics from ECR exporter and set-up alerts to their own channel.

## Proposed user journey

Update the user-guide for users to use the ECR metrics from ECR exporter and set-up alerts.
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/ecr-setup.html#managing-your-ecr-repository

## Approach

User guide should guide user on how to set up ECR alerts also an example of prometheus ECR alerts.

```
    - alert: ECR-Imagecount_Amber-Alert
      expr: aws_ecr_repository_image_count > 500
      for: 10m
      labels:
        severity: warning
      annotations:
        message: Image count for the Repository {{ $labels.repository_name }} is more than 500.
        runbook_url: https://docs.aws.amazon.com/AmazonECR/latest/userguide/service_limits.html
```

## Which part of the user docs does this impact

https://user-guide.cloud-platform.service.justice.gov.uk/documentation/getting-started/ecr-setup.html#managing-your-ecr-repository

## Questions / Assumptions

Removing ECR alerts from low priority, so users maintain their own alerts using the guidence.

## Definition of done

- [ ] user docs have been updated
- [ ] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
If users channel information is available as part of cloud-platform-cli, Using cloud-platform-cli to create ECR can also set prometheus alert in the user's namespace by default when user create a ECR repository.

```
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-custom-alerts-ecr-exporter
  namespace: monitoring
  labels:
    prometheus: prometheus-operator
    role: alert-rules
spec:
  groups:
  - name: ecr-monitoring
    rules:
    - alert: ECR-Imagecount_Amber-Alert
      expr: aws_ecr_repository_image_count > 500
      for: 10m
      labels:
        severity: <user-channel>
      annotations:
        message: Image count for the Repository {{ $labels.repository_name }} is more than 500.
        runbook_url: https://docs.aws.amazon.com/AmazonECR/latest/userguide/service_limits.html
```
