### ISSUE TITLE
Teams Ingress-controller- provide more options for users

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#2280]
Teams Ingress-controller- provide more options for users

Now teams will be using their own ingress controller for their namespace. Now they can use their own values file, but it might be hard for users to understand and use their own values file. We can find a list of things they might need changing and provide them as option to change. 

https://github.com/ministryofjustice/cloud-platform-terraform-teams-ingress-controller

Discussion here:
https://mojdt.slack.com/archives/C514ETYJX/p1598525564425600

Some of them for example:

- Default Backend option

```defaultBackend:
  enabled: true

  name: default-backend
  image:
    repository: ministryofjustice/cloud-platform-custom-error-pages
    tag: "0.4"
    pullPolicy: IfNotPresent
```

- Other config

```
  config:
    enable-modsecurity: "true"
    custom-http-errors: 413,502,503,504
    proxy-buffer-size: "16k"
    proxy-body-size: "50m"
    # Config below is for old TLS versions. Specifically an incident with IE11 on
    # bank-admin.prisoner-money.service.justice.gov.uk. More info CP Incidents page.
    ssl-ciphers: option?
    ssl-protocols: option?
```
