### ISSUE TITLE
Create second ingress for all ingress using default ingress controller

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#2397]
This is related to [2339](https://github.com/ministryofjustice/cloud-platform/issues/2339)

There is a down time while upgrading our default ingress controller.
https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx#migrating-from-stablenginx-ingress

To avoid downtime.

Steps: 

1) Create second Ingress controller
**2) Create second ingress for all ingress using default ingress controller and change 
their name and ingress class to use second ingress controller**
3) Change all the txt records created by external-dns to point to new ingress name.
4) external-dns will trigger and update the new NLB information for the A records in the route53 zone
5) Upgrade 2nd Ingress controller
6) Change all the txt records created by external-dns to point to old ingress name.
7) external-dns will trigger and update the old NLB information for the A records in the route53 zone
8) Delete new ingress created
9) Delete new ingress controller

This ticket is to create second ingress for all ingress using default ingress controller 

prerequisite:
1) Second ingress controller is created successfully

Approach:

Create 2nd ingress for all the ingress using default-ingress controller.

1) In the ingress definition, use the class name of the 2nd ingress-controller.
2) Give a different name to the original ingress name.
3) make sure the ingress is just a copy of the original one (except class and ingress name)
4) Communicate with the users related to the second ingress in their namespace.

5) Apply that in live-1, now we will 2 ingress for each namespace which uses default ingress-controller.

Applying this will have nearly 600 ingress in the cluster, so keep an eye on performance of the ingress-controllers and the K8's API

```
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: <helloworld-rubyapp-ingress>  update this to for ex:  <helloworld-rubyapp-ingress2>
  namespace: user-namespace
  annotations:
    kubernetes.io/ingress.class: <nginx>  update this to for ex:  <nginx2>
spec:
  tls:
  - hosts:
    - ing-class.cloud-platform.service.justice.gov.uk
    secretName: tls-short-domain
  rules:
  - host: ing-class.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: rubyapp-service
          servicePort: 4567
```
