### ISSUE TITLE
FIREBREAK: Investigate Terraform operator

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#2808]
## Background

We use Terraform to deploy a LOT, if not all, of our Kubernetes infrastructure via Terraform. It would be nice if we had a Kubernetes controller to ensure persistence of that infrastructure. 
Source: https://github.com/isaaguilar/terraform-operator?utm_sq=gnntjoiqkk
_A way to run Terraform in Kubernetes by defining Terraform deployments as Kubernetes manifests
A controller that configures and starts Kubernetes Jobs when it sees changes to the Kubernetes manifest
A Terraform runner which runs Terraform plan/apply, and can also perform pre and post scripts_

## Questions / Assumptions

That there is an easy way to install the operator and it's easy to maintain.
Does the operator work for things outside of the cluster, do we want it to?
What are some of the positives/negatives of using this operator to deploy our Terraform state?

## Definition of done

- [ ] Firebreak finding documented appropriately
- [ ] Demo completed
- [ ] Decision made on whether to progress Firebreak work
- [ ] Firebreak next step Issues created
- [ ] New Issues referenced in this story before closure

**Comment by razvan-moj** [comment]
PRO: Works, and quite nicely.
An example would be 
```
---
apiVersion: tf.isaaguilar.com/v1alpha1
kind: Terraform
metadata:
  name: cp-test-zzz-s3
  namespace: zzz
spec:
  # https://hub.docker.com/r/isaaguilar/tfops
  terraformVersion: 0.14.7
  terraformRunnerPullPolicy: IfNotPresent
  customBackend: |-
    terraform {
      backend "kubernetes" {
        secret_suffix    = "s3"
        in_cluster_config  = true
        namespace = "zzz"
      }
    }
  terraformModule:
    address: https://github.com/ministryofjustice/cloud-platform-terraform-s3-bucket?ref=4.6
  applyOnCreate: true
  applyOnUpdate: true
  applyOnDelete: true
  ignoreDelete: false
  credentials:
  - secretNameRef:
      name: aws-session-credentials
  env:
  - name: AWS_REGION
    value: eu-west-2
  - name: TF_VAR_bucket_name
    value: cp-test-zzz-two
  - name: TF_VAR_namespace
    value: zzz
  - name: TF_VAR_application
    value: cp-test-zzz-s3
  - name: TF_VAR_environment-name
    value: cp-test-zzz-s3
  - name: TF_VAR_team_name
    value: cp-test-zzz-s3
  - name: TF_VAR_infrastructure-support
    value: cp-test-zzz-s3
```
CONS:
 - applies one module at a time, inter-module variable passing and sharing state can be tricky
 - It would be quite disruptive for our workflows, especially the approval part

Conclusion: would be very useful to revisit if/when we have a dev/prod environment separation, dev being more self-service while prod would keep restrictions, pipeline and approvals.
