### ISSUE TITLE
Linting for YAML files used for Cloud Platform Environments

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#293]
## Background

User comments in the #cloud-platform-users channel have suggested that yaml code errors coule be picked up by linting. 

![image](https://user-images.githubusercontent.com/36888942/43520807-e90f2a0e-958b-11e8-9d2d-a9d0a1fac909.png)

Linting is the process of running a program that will analyse code for potential errors. Identifying potential errors using linting will improve the quality of code and reduce errors.

There are plenty of existing linting tools available.

## Approach

TBC

## Definition of done

- [x] Linting added for YAML files
- [x] user can see output of linting

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by nayoa** [comment]
```   yaml: 
    docker: 
      - image: ubuntu:16.04
    steps:
      - checkout
      - run: 
          name: Install depedencies 
          command: | 
            apt-get update
            apt-get -y install yamllint python3-pkg-resources git-crypt locales
      - deploy:
          name: git-crypt
          command : |
            echo "${GIT_CRYPT_KEY}" | base64 -d > git-crypt.key
            git-crypt unlock git-crypt.key
      - deploy:
          name: Run yamllint
          command: | 
            locale-gen en_US.UTF-8
            export LANG=en_US.UTF-8
            yamllint .
```
The above test allows CircleCI to run `yamllint` on the `cloud-platform-environments` repository. A further `.yamllint` config file was required to ignore specific rules. However, it appeared that every file was not indented properly and the goal of the ticket was to fail a check if the kubernetes manifest file was incorrect : 

``` extends: default
rules:
  line-length: disable  # don't bother me with this rule
  document-start: disable
  new-line-at-end-of-file: disable
  new-lines: disable
  trailing-spaces: disable
  colons: disable
  indentation:
    level: warning
  empty-lines:
    level: warning```

Contenders like https://github.com/garethr/kubeval were perfect for this. However, as we use coreos monitoring schema, some manifests failed the check as `kubeval` would only use the Kubernetes or Openshift schema.
