### ISSUE TITLE
Investigate modsec ingress controller failure

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#3214]
## Background

For two days in a row an error has triggered (redacted for public):

```
[FIRING:1] :warning: NginxConfigReloadFailureWarning
Alert: The Nginx Config has failed to reload for pod modsec01-nx-controller
     Details:
      - alertname: NginxConfigReloadFailureWarning
      - clusterName: live-1
      - container: controller
      - endpoint: metrics
      - job: modsec01-nx-controller-metrics
      - namespace: ingress-controllers
      - service: modsec01-nx-controller-metrics
      - severity: warning
     -----
```

Upon investigation we're able to witness the symptom but not the cause, please see thread in source below. 

Source:
https://mojdt.slack.com/archives/C8QR5FQRX/p1632130768034000 - alarm
https://mojdt.slack.com/archives/C514ETYJX/p1632131150064200 - slack investigation thread

## Proposed user journey

Investigate why the alarm keeps triggering and find the root cause.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
