### ISSUE TITLE
Migration docs: cope with circleci configs that use "setup-kube-auth"

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/cloud-platform#3252]
CP's guidance for setting up CircleCI used to tell people to use `setup-kube-auth` script. Lots of people still have it in their config, BUT it's now unmaintained. In our migration this may cause confusion and support requests.

Let's explain create a guidance page separate to the migration, telling people how they should update their CircleCI config.

i.e. somethign like: if you see in your CircleCI script:
```
    - image: ${ECR_ENDPOINT}/cloud-platform/tools:circleci
  steps:
    - checkout
    - deploy:
        name: Helm deployment
        command: |
          setup-kube-auth
```
Then you need to switch it to the new CircleCI method of auth.

Tools image is not maintained and needs updating to the new way of auth - see example: https://github.com/ministryofjustice/cloud-platform-reference-app/blob/main/.circleci/config.yml 

Maybe show a diff of the change?

And reference this in the migration docs.

## Definition of done

- [ ] new guidance created showing how to update circleci
- [ ] migration guidance references it in [Step 6](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/migrate-to-live.html#prerequisites-for-migration).
- [ ] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
