### ISSUE TITLE
Explore DeadMansSwitch alert of Prometheus

### ISSUE THREAD

**Issue by poornima-krishnasamy** [ministryofjustice/cloud-platform#3543]
## Background

Alertmanager recently throw errors when it couldnot send alerts to a private slack channel with webhook now working. 

Investigate whether DeadManSwitch alert from prometheus will help alert and monitor Alertmanager when it undergo these kind of issues.

(https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/blob/main/templates/prometheus-operator-eks.yaml.tpl#L52)

## Which part of the user docs does this impact

https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/tree/main/resources/prometheusrule-alerts

## Definition of done

- [ ] DeadMansSwitch alert configured and an external system been setup to receive those alerts 
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
There is a free 1-alert service at https://deadmanssnitch.com/account/sign_up?plan=the_lone_snitch with an API described at https://deadmanssnitch.com/docs/api/v1

**Comment by vijay-veeranki** [comment]
Tried with https://deadmanssnitch.com/snitches/

Using below config:

```
      - match:
          alertname: DeadMansSwitch
        receiver: 'cole'

    receivers:
    - name: 'null'
    - name: 'cole'
      webhook_configs:
      - url: 'https://nosnch.in/xxxxxx'
```

crated alert

`     - alert: DeadMansSwitch
       annotations:
         description: This is a DeadMansSwitch meant to ensure that the entire Alerting
           pipeline is functional.
         summary: Alerting DeadMansSwitch
       expr: vector(1)
       labels:
         severity: none
`

I can see an alert in alert manger, but can't see any email triggered from "https://deadmanssnitch.com/snitches"
