### ISSUE TITLE
Spike: Create another load balancer and split traffic

### ISSUE THREAD

**Issue by jasonBirchall** [ministryofjustice/cloud-platform#3954]
## Background

> On 11th July 2022, users start reporting a portion of their traffic is not responding or timing out. The previous day (10/07/22) saw AWS restart a large number of nodes due to a “thermal incident” (TAM). This new report resulted from a network interface in the live-1 VPC responding successfully to around 75% of traffic (rough estimate). This caused a degradation for all services in the Cloud Platform for approximately 6 hours and 37 minutes. 

We must find a way to mitigate this in the future.

Source: https://docs.google.com/document/d/1QR31_9Ga_LdXSzgoFjiemE-jxq5sf59rKj5gAoNTU9E/edit#

Following a post-incident review, the team came up with the following action:

Alongside our default ingress controller, create a new controller and split traffic across both using an ingress weighting annotation.

## Proposed user journey

As a cloud-platform developer, demonstrate the ease of installation and maintenance of an additional ingress controller. This would ideally live in the ingress-controllers namespace and be aptly named.

As a developer/user of the platform. I want my traffic to survive a failure of a load-balancer/ingress controller. I want to keep the amount of failover maintenance to a minimum, and ideally, just be informed of an occurrence.

## Approach

- [ ] Create a duplicate ingress controller
- [ ] Split the traffic on a test application using annotation weighting on an ingress rule.
- [ ] Perform a failure scenario and measure the impact of a controller/load-balancer failing.
- [ ] See how easy this is to recover.
- [ ] Document and perform a demonstration for the next steps.

## Which part of the user docs does this impact

- [ ] Perhaps the installation documentation.
- [ ] Document any code, citing the active, active nature of dual ingress controllers.

## Questions / Assumptions

[assumption] that this will mitigate a failure of an ingress controller/load balancer.

[question] are we able to simply remove one of the controllers without any impact on the end user.

## Definition of done

- [ ] New controller exists in a test cluster
- [ ] Failure scenarios have been carried out
- [ ] The failure process and procedure is documented and demonstrated

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
Investigation completed. Steps carried out as follows:

- Created test cluster with an additional module call to create a second default ingress-controller in `ingress-controllers` namespace with `controller-name = "default-2"`

- Deploy sample application (sample Ruby helloworld) with an extended ingress definition to provide annotation weighting rules across both load balancers:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: helloworld-ingress-test-green
    external-dns.alpha.kubernetes.io/aws-weight: "50"
spec:
  ingressClassName: default
  tls:
  - hosts:
    - helloworld.apps.cp-2807-0942.cloud-platform.service.justice.gov.uk
  rules:
  - host: helloworld.apps.cp-2807-0942.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - backend:
          service:
            name: rubyapp-service
            port:
              name: http
        pathType: ImplementationSpecific
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-2
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: helloworld-2-ingress-test-green
    external-dns.alpha.kubernetes.io/aws-weight: "50"
spec:
  ingressClassName: default-2
  tls:
  - hosts:
    - helloworld.apps.cp-2807-0942.cloud-platform.service.justice.gov.uk
  rules:
  - host: helloworld.apps.cp-2807-0942.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - backend:
          service:
            name: rubyapp-service
            port:
              name: http
        pathType: ImplementationSpecific
```

- Test failure scenario of single ingress-controller loss via deleting one of the default ingress Helm deployments, and utilising Raz's curl loop trick on both LB addresses and also against just the application hostname simultaneously.

- In two runs of the above scenario, I observe the curl on the deleted load balancer timeout, and at the same point in time also observe a timeout on `curl helloworld.apps.cp-2807-0942.cloud-platform.service.justice.gov.uk`. In both instances the latter curl recovered within 50-60 seconds at which point resolution stabilised.
