### ISSUE TITLE
Can external dns share between clusters?

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4104]
## Background

Can external dns share between clusters? 

Note - Same hosts should not be created in both clusters.

## Definition of done

- [ ] We've confirmed if external dns can be shared across clusters.
- [ ] If not, we can write stories for next steps.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by razvan-moj** [comment]
@poornima-krishnasamy short answer - yes. Any ingress definition with a weight eg
```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: hello-raz-starter-pack-0-orange
    external-dns.alpha.kubernetes.io/aws-weight: "100"
  name: hello-raz
  namespace: starter-pack-0
spec:
  ingressClassName: default
  rules:
  - host: hello-raz.integrationtest.service.justice.gov.uk
    http:
      paths:
      - backend:
          service:
            name: helloworld
            port:
              name: http
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - hello-raz.integrationtest.service.justice.gov.uk
    secretName: hello-raz-ssl
```
will work and overwrite existing or show up along the other cluster's entry
