### ISSUE TITLE
Add ebs csi node affinity for Prometheus and alert-manager

### ISSUE THREAD

**Issue by vijay-veeranki** [ministryofjustice/cloud-platform#4275]
When the cluster is upgraded to 1.23, we have an issue with Prometheus pods. We get the below error

Prometheus pod stuck in pending with error:
  Normal   NotTriggerScaleUp  39s (x104 over 20m)  cluster-autoscaler  pod didn't trigger scale-up: 1 node(s) didn't match Pod's node affinity/selector, 1 node(s) had volume node affinity conflict

The reason is Prometheus is created in a separate node group in availability zone eu-west-2b and the new csi driver is expecting a node affinity.
https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html

Add ebs csi node affinity for Prometheus

```
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cloud-platform.justice.gov.uk/monitoring-ng
              operator: In
              values:
              - "true"
          - matchExpressions:
            - key: topology.ebs.csi.aws.com/zone
              operator: In
              values:
              - "eu-west-2b"
```

Add a similar to alert-manager and move it to the monitoring node.

This is not needed when getting the pods connected to volume, but it is suggestible to create a new class with allowed_topologies and use this class for monitoring the module

```
resource "kubernetes_storage_class" "gp3-monitoring" {
  metadata {
    name = "gp3-monitoring"
  }
  storage_provisioner    = "ebs.csi.aws.com"
  reclaim_policy         = "Delete"
  allow_volume_expansion = "true"

  parameters = {
    type      = "gp3"
    encrypted = "true"
  }
  
  allowed_topologies {
    match_label_expressions {
      key = "topology.kubernetes.io/zone"
      values = [
        "eu-west-2b",
      ]
    }
  }
}
```
