### ISSUE TITLE
SPIKE: Generate self-signed X509 certificates

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#4315]
## Background

We've had a [request from a user](https://mojdt.slack.com/archives/C57UPMZLY/p1673606749461469) to be able to generate/store/rotate self-signed X509 certificates (pub/priv pairs). The current certificate offering doesn't meet that need.

User case:

> The use case in particular for us would be to generate a set of X509 certs (and potentially automate the rotation, although this is not that important as these can be long lived) used for the signing and decryption of SAML payloads when integrating with other system. They expose their public cert, we expose our public cert, and then we assess and decrypt each others payloads (signatures).

For testing/user feedback contact Jesus Laiz

## Proposed user journey

As user can create and manage their own self-signed X509 certificates

## Approach

This is a spike to look at what is possible. We should look to enable users to self service and make these easy to adopt. 

We have some options to investigate:
https://phoenixnap.com/kb/kubernetes-ssl-certificates
https://cert-manager.io/docs/configuration/selfsigned/

Some team discussion - https://mojdt.slack.com/archives/C514ETYJX/p1673948337485129

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

- Solution works with Cert Manager?
- user could manage the issuer in their namespace?
- What would the user journey look like?

## Definition of done

- [ ] We can confirm is we can offer users self-signed X509 certificates
- [ ] We are able to create story for implementation.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by vijay-veeranki** [comment]
https://github.com/ministryofjustice/cloud-platform-terraform-certmanager/pull/32

Users can create a cert and issuer in the namespace as below

```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-selfsigned-ca
  namespace: sandbox
spec:
  isCA: true
  commonName: my-selfsigned-ca
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: my-ca-issuer
  namespace: sandbox
spec:
  ca:
    secretName: root-secret
```
