### ISSUE TITLE
Kuberhealthy Alerts Review

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#4670]
Review Kuberhealthy alerts

We have been getting a number of false positives which led to some alerts being ignored which can mask real issues. 

Identify alerts that cause false alerts and look into either removing the alerts, amending the alert and creating a new alert in its place.

We should be acknowledging all alerts with an action to why it alerted.

**Comment by pwyborn** [comment]
From research I have carried out.
I have not found one incident or occasion where Kuberhealthy has been an early warning to something happening -
other alerts have either reported earlier and/or Kuberhealthy has given alerts in the early morning that are not indicators of issues.
Also there have been no further work carried out on Kuberhealthy and the indications here are that it is only being maintained by 1 person who has little time to give to it.
```
djsly commented 4 days ago
@integrii @joshulyne @jonnydawg
Can you confirm is this project is dead and you don't expect to be contributing and keeping it a CNCF project ?

@integrii
Collaborator
integrii commented 4 days ago
I would like to refresh this project and keep it going. I think a good weekend of focus would bring it up to date. I've been the sole maintainer for some time and life has kept me pretty busy (4 kids). I think @jonnydawg also may be interested in contributing again. We had a conversation about that this week.

```
https://github.com/kuberhealthy/kuberhealthy/issues/1144

**Comment by pwyborn** [comment]
Incident on 21st of July may contradict what I have just said.
Checks:

1. [Daemonset Check](https://github.com/kuberhealthy/kuberhealthy/blob/master/cmd/daemonset-check/README.md#daemonset-check) - A failure occured somewhere in the daemonset deployment or tear down, an error is shown on the status page describing the issue "kubectl -n kuberhealthy describe khstate daemonset". Also check failing checker pod logs.
`The check runs every 15 minutes (spec.runInterval), with a check timeout set to 12 minutes (spec.timeout). If the check
does not complete within the given timeout it will report a timeout error on the status page.`
&nbsp;
&nbsp;
2. [Deployment](https://github.com/kuberhealthy/kuberhealthy/blob/master/cmd/deployment-check/README.md#deployment-and-service) - An error occurred somewhere in the deployment creation, service creation, HTTP request, or tear down process -- resulting in an error report to the Kuberhealthy status page "kubectl -n kuberhealthy describe  khstate deployment". Also check failing checker pod logs.
`The check runs every 10 minutes (spec.runInterval), with a check timeout set to 15 minutes (spec.timeout). If the check
does not complete within the given timeout it will report a timeout error on the status page.
&nbsp;
&nbsp;
3. [DNS Status Check](https://github.com/kuberhealthy/kuberhealthy/blob/master/cmd/dns-resolution-check/README.md#dns-status-check) - hecks for failures with DNS, including resolving within the cluster "kubectl -n kuberhealthy describe khstate dns-status-internal". Also check failing checker pod logs
`The check runs every 2 minutes (spec.runInterval), with a check timeout set to 15 minutes (spec.timeout). If the check does not complete within the given timeout it will report a timeout error on the status page.`
&nbsp;
&nbsp;
4. OverallClusterStateCheck - Check for any Kuberhealthy checks with status "fail". "kubectl -n kuberhealthy get khstate". Also check failing pod logs
&nbsp;
&nbsp;
5. [Namespace Check](https://github.com/ministryofjustice/cloud-platform-kuberhealthy-checks/tree/main#namespace-check)  - One of the following vital namespaces no longer exists - "cert-manager", "default", "ingress-controllers", "kube-system", "logging", "monitoring", "opa", "velero", "kubectl -n kuberhealthy describe khstate namespace-kh-check". Also check failing pod logs.
`The checks are run using a crd definition every 30 sec (spec.runInterval), with a check timeout set to 2m (spec.timeout). If the check does not complete within the given timeout it will report a timeout error on the status page.`

**Comment by pwyborn** [comment]
1.  Daemonset config
```
#### Daemonset Check Kube Spec:

```$xslt
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: daemonset
  namespace: kuberhealthy
spec:
  runInterval: 15m
  # Make sure this Kuberhealthy check timeout is GREATER THAN the daemonset checker timeout
  # set in the env var CHECK_POD_TIMEOUT. Default is set to 5m (5 minutes).
  timeout: 12m
  extraAnnotations:
    comcast.com/testAnnotation: test.annotation
  extraLabels:
    testLabel: testLabel
  podSpec:
    containers:
      - env:
          - name: POD_NAMESPACE
            value: "kuberhealthy"
          - name: NODE_SELECTOR # Schedules daemonsets only to nodes with this label
            value: "kubernetes.io/os=linux"
        image: kuberhealthy/daemonset-check:v3.3.0
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
```

2. Deployment Config:
```
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: deployment
  namespace: kuberhealthy
spec:
  runInterval: 10m
  timeout: 15m
  podSpec:
    containers:
      - name: deployment
        image: kuberhealthy/deployment-check:v1.9.0
        env:
          - name: CHECK_IMAGE
            value: "nginx:1.17-perl"
          - name: CHECK_IMAGE_ROLL_TO
            value: "nginx:1.17.5-perl"
          - name: CHECK_DEPLOYMENT_REPLICAS
            value: "4"
          - name: CHECK_DEPLOYMENT_ROLLING_UPDATE
            value: "true"
        resources:
          requests:
            cpu: 25m
            memory: 15Mi
          limits:
            cpu: 1
    restartPolicy: Never
    serviceAccountName: deployment-sa
    terminationGracePeriodSeconds: 60
```
3. DNS Status Config:
```
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: dns-status-internal
  namespace: kuberhealthy
spec:
  runInterval: 2m
  timeout: 15m
  podSpec:
    containers:
      - env:
          - name: HOSTNAME
            value: "kubernetes.default"
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        image: kuberhealthy/dns-resolution-check:v1.5.0
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
```
4. Overall Cluster config:
5. Namespace Config status:
our own custom config at https://github.com/ministryofjustice/cloud-platform-kuberhealthy-checks/tree/main/cmd/namespace-check

**Comment by pwyborn** [comment]
NamespaceExists changes (to purely report on missing namespaces (rather than report on problems with Kuberhealthy itself):
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/176
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/2474

**Comment by pwyborn** [comment]
**Deployment Check (for info)**
https://github.com/kuberhealthy/kuberhealthy/blob/master/cmd/deployment-check/README.md#deployment-and-service
## Deployment and Service 

This check tests if a `deployment` and `service` can be created within your Kubernetes cluster. It will attempt to bring up a `deployment` with `2` replicas and a `service` of type `ClusterIP` in the `kuberhealthy` namespace and waits for the pods to come up. Once the `deployment` is ready, the check makes a request to the hostname looking for a `200 OK`. The check then proceeds to terminate them and ensures that the `deployment` and `service` terminations were successful. A complete tear down of the `deployment` and `service` after receiving a `200 OK` marks a successful test run.

Container resource requests are set to `15 millicores` of CPU and `20Mi` units of memory and typically use an Nginx's image for the `deployment`. If the environment variable `CHECK_DEPLOYMENT_ROLLING_UPDATE` is set to `true`, the check will attempt to perform a rolling-update on the `deployment`. Once this rolling-update completes, the check makes another request to the hostname looking for a `200 OK` again before cleaning up. By default, the check will initially deploy Nginx's unprivileged `nginxinc/nginx-unprivileged:1.17.8` image, and update to `nginxinc/nginx-unprivileged:1.17.9`.

Custom images can be used for this check and can be specified with the `CHECK_IMAGE` and `CHECK_IMAGE_ROLL_TO` environment variables. If a custom image requires the use of environment variables, they can be passed down into your container by setting the environment variable `ADDITIONAL_ENV_VARS` to a string of comma-separated values (`"X=foo,Y=bar"`).

The number of replicas the `deployment` brings up can be adjusted with the `CHECK_DEPLOYMENT_REPLICAS` environment variable. By default the amount of replicas used is `2`, but this can be customized for different scenarios and environments. `maxSurge` and `maxUnavailable` values for the `deployment` is calculated to be `%50` of the `deployment` replicas (_rounded-up_).

A successful run implies that a `deployment` and service can be brought up and the corresponding hostname endpoint returns a `200 OK` response. A failure implies that an error occurred anywhere in the deployment creation, service creation, HTTP request, or tear down process -- resulting in an error report to the _Kuberhealthy_ status page.

#### Deployment Check Diagram

![](../../images/kh-deployment-check.gif)

#### Check Steps

This check follows the list of actions in order during the run of the check:

1.  Looks for old `services` and `deployments` belonging to this check and cleans them up.
2.  Creates a `deployment` configuration, applies it to the namespace, and waits for the `deployment` to come up.
3.  Creates a `service` configuration, applies it to the namespace, and waits for the `service` to come up.
4.  Makes an HTTP Get request to the `service` endpoint, looking for a `200 OK`.

**IF ROLLING-UPDATE OPTION IS ENABLED**

5.  Creates an updated `deployment` configuration, applies it to the namespace, and waits for the deployment to complete its rolling-update.
6.  Makes a second HTTP Get request to the `service` endpoint, looking for another `200 OK`.

#### Check Details

- Namespace: kuberhealthy
- Timeout: 15 minutes
- Check Interval: 30 minutes
- Check name: `deployment`

#### Check Configuration Environment Variables

- `CHECK_IMAGE`: Initial container image. (default=`nginxinc/nginx-unprivileged:1.17.8`)
- `CHECK_IMAGE_ROLL_TO`: Container image to roll to. (default=`nginxinc/nginx-unprivileged:1.17.9`)
- `CHECK_IMAGE_PULL_SECRET`: Name of Image Pull Secret to use for above images. 
- `CHECK_DEPLOYMENT_NAME`: Name for the check's deployment. (default=`deployment-deployment`)
- `CHECK_SERVICE_NAME`: Name for the check's service. (default=`deployment-svc`)
- `CHECK_NAMESPACE`: Namespace for the check (default=`kuberhealthy`) The namespace that the `khcheck` CRD lives in will override this value.
- `CHECK_DEPLOYMENT_REPLICAS`: Number of replicas in the deployment (default=`2`).
- `CHECK_DEPLOYMENT_ROLLING_UPDATE`: Boolean to enable rolling-update (default=`false`).
- `CHECK_CONTAINER_PORT`: Check pod container port (default=`8080`).
- `CHECK_POD_CPU_REQUEST`: Check pod deployment CPU request value. Calculated in decimal SI units (`15 = 15m cpu`).
- `CHECK_POD_CPU_LIMIT`: Check pod deployment CPU limit value. Calculated in decimal SI units (`75 = 75m cpu`).
- `CHECK_POD_MEM_REQUEST`: Check pod deployment memory request value. Calculated in binary SI units (`20 * 1024^2 = 20Mi memory`).
- `CHECK_POD_MEM_LIMIT`: Check pod deployment memory limit value. Calculated in binary SI units (`75 * 1024^2 = 75Mi memory`).
- `NODE_SELECTOR`: Comma separated list of `key=value` node selector values for the deployment check. By default, there are no selectors.
- `TOLERATIONS`: Toleration values to respect on the deployment. By default, there are no tolerations.
- `ADDITIONAL_ENV_VARS`: Comma separated list of `key=value` variables passed into the pod's containers.
- `SHUTDOWN_GRACE_PERIOD`: Amount of time in seconds the shutdown will allow itself to clean up after an interrupt signal (default=`30s`).
- `DEBUG`: Verbose debug logging.


#### Example KuberhealthyCheck Spec

The following configuration will create a deployment with 4 replicas and roll from `nginx:1.17-perl` to `nginx:1.17.5-perl`:

```yaml
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: deployment
  namespace: kuberhealthy
spec:
  runInterval: 10m
  timeout: 15m
  podSpec:
    containers:
      - name: deployment
        image: kuberhealthy/deployment-check:v1.9.0
        env:
          - name: CHECK_IMAGE
            value: "nginx:1.17-perl"
          - name: CHECK_IMAGE_ROLL_TO
            value: "nginx:1.17.5-perl"
          - name: CHECK_DEPLOYMENT_REPLICAS
            value: "4"
          - name: CHECK_DEPLOYMENT_ROLLING_UPDATE
            value: "true"
        resources:
          requests:
            cpu: 25m
            memory: 15Mi
          limits:
            cpu: 1
    restartPolicy: Never
    serviceAccountName: deployment-sa
    terminationGracePeriodSeconds: 60
```

The following configuration will create a deployment with 6 replicas and roll from `nginxinc/nginx-unprivileged:1.17.8` to `nginxinc/nginx-unprivileged:1.17.9`:

```yaml
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: deployment
  namespace: kuberhealthy
spec:
  runInterval: 10m
  timeout: 15m
  podSpec:
    containers:
      - name: deployment
        image: kuberhealthy/deployment-check:v1.9.0
        env:
          - name: CHECK_DEPLOYMENT_REPLICAS
            value: "6"
          - name: CHECK_DEPLOYMENT_ROLLING_UPDATE
            value: "true"
        resources:
          requests:
            cpu: 25m
            memory: 15Mi
          limits:
            cpu: 1
    restartPolicy: Never
    serviceAccountName: deployment-sa
    terminationGracePeriodSeconds: 60
```

#### Install

To use the _Deployment Check_ with Kuberhealthy, apply the configuration file [deployment-check.yaml](deployment-check.yaml) to your Kubernetes Cluster. The following command will also apply the configuration file to your current context:

`kubectl apply -f https://raw.githubusercontent.com/kuberhealthy/kuberhealthy/master/cmd/deployment-check/deployment-check.yaml`

The check configuration file contains:

- KuberhealthyCheck
- Role
- Rolebinding
- ServiceAccount

The role, rolebinding, and service account are all required to create and delete all deployments and services from the check in the given namespaces you install the check for. The assumed default service account does not provide enough permissions for this check to run.
