### ISSUE TITLE
Add mutating webhook yaml to `https://github.com/ministryofjustice/cloud-platform-label-pods`

### ISSUE THREAD

**Issue by jaskaransarkaria** [ministryofjustice/cloud-platform#5123]
## Background

add mutating webhookconfiguration yaml to https://github.com/ministryofjustice/cloud-platform-label-pods

This will enable all pods in the cluster to be labelled with their github_team, this is needed so users can see their logs and only their logs

```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: label-pods-with-github-team
  labels:
    name: api
  annotations:
    cert-manager.io/inject-ca-from: cloud-platform-label-pods/serving-cert
webhooks:
  - name: api.cloud-platform-label-pods.svc.cluster.local
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["cloud-platform-label-pods"]
    failurePolicy: Ignore
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"] 
    clientConfig:
      caBundle: Cg== 
      service:
        name: api
        namespace: cloud-platform-label-pods
        path: "/mutate/pod"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
```

~~A second piece of work to be completed at the same time is whitelist system namespaces by specifying the github_team as "all-org-members"~~

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
