### ISSUE TITLE
Update cloud-platform-maintenance-page docker-build workflow file

### ISSUE THREAD

**Issue by timckt** [ministryofjustice/cloud-platform#5777]
## Background

In [cloud-platform-maintenance-page](https://github.com/ministryofjustice/cloud-platform-maintenance-page), the [github workflow](https://github.com/ministryofjustice/cloud-platform-maintenance-page/blob/main/.github/workflows/docker-build.yaml) is using pushing image to DockerHub rather than ECR. 

It is not updated and not align with the Readme file which mentions `Configure the Github actions to build the maintenance page image to your ECR`.

```
jobs:
  docker:
    name: Build container and push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Tags for Image
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ministryofjustice/cloud-platform-maintenance-page
          tags: |
            type=ref,event=tag

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
```

Update it to be ECR focused and align with the Readme instruction.

Workflow reference [here](https://github.com/ministryofjustice/cloud-platform-example-application/blob/main/.github/workflows/deploy.yml) for pushing to ECR

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
