### ISSUE TITLE
Add snyk to cloud platform tools image

### ISSUE THREAD

**Issue by jsugarman** [ministryofjustice/cloud-platform#5849]
## Service name

Submit a crime form

## Service environment

- [ ] Dev / Development
- [ ] Staging
- [ ] Prod / Production
- [X] Other (CircleCI)

## Impact on the service

No impact

## Problem description

Hi CP,

Would it be possible to install the snyk CLI as part of the cloud-platform-tools-image. This would allow testing helm templates using `synk iac test` using that images libs.

Testing the k8s manifests using snyk requires generating them to an output file (using helm's templating engine), then passing the output to snyk to "test". example below.  This would provide a couple of advantages - currently I have to install helm in our circleci  test-executor in order to use it,  so more to install, more to maintain, disconnect from actual helm version used for deploy. If the cp tool image had it i could just use that executor, avoiding an install step and transparently using the same version of helm used for deployment.

current mechanism:
```yaml
orbs:
  helm: circleci/helm@3.0.2
...
  scan-docker-image:
    executor: test-executor
    steps:
      .....
      - helm/install_helm_client:
          version: 3.7.2
      - run:
          name: Test IaC files
          command: |
            # render k8s manifests from helm templates
            helm template ./helm_deploy --output-dir ./output --values helm_deploy/values-prod.yaml

            snyk iac test ./output --report --policy-path=.snyk --severity-threshold=high
```

possible mechanism 🤞 
```yaml
...
  scan-docker-image:
    executor: cloud-platform-executor
    steps:
      .....
      - run:
          name: Test IaC files
          command: |
            # render k8s manifests from helm templates
            helm template ./helm_deploy --output-dir ./output --values helm_deploy/values-prod.yaml

            snyk iac test ./output --report --policy-path=.snyk --severity-threshold=high

```

## Contact person

Slack: `@Joel Sugarman`
