### ISSUE TITLE
Support Blue/ Green deployments via AWS weight annotation across multiple namespaces

### ISSUE THREAD

**Issue by BenMillar-MOJ** [ministryofjustice/cloud-platform#6785]
## Issue

We would like to deploy a new version of service using a blue/ green deployment pattern.

To achieve this we need to create multiple ingresses, in different namespaces, with the same hostname. This is currently disallowed by a gatekeeper rule.

## Potential blockers

Other users should be unable to create an ingress using our hostname without permission being granted via the primary namespace.

### Additional context
[https://mojdt.slack.com/archives/C57UPMZLY/p1738076217443909?thread_ts=1738067857.948439&cid=C57UPMZLY](https://mojdt.slack.com/archives/C57UPMZLY/p1738076217443909?thread_ts=1738067857.948439&cid=C57UPMZLY)

## Contact person

Please contact us in #laa-cla-dev if you have any questions.

Many thanks for this, it is greatly appreciated! 😄

**Comment by timckt** [comment]
- Created the [testing branch](https://github.com/ministryofjustice/cloud-platform-terraform-gatekeeper/tree/blue-green-deployment).

Deployed the change in the test cluster.

Although we have update the gatekeeper constraint, we need to add additional annotation or else we will face the below error when deploying the duplicate ingress with the same host and same path.
```
for: "STDIN": error when patching "STDIN": admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "helloworld.cp-2402-0759.cloud-platform.service.justice.gov.uk" and path "/" is already defined in ingress starter-pack-0/helloworld-blue
```

**_Fail case_** blue ingress:

```
→ kubectl apply -f - <<EOF
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-blue
  namespace: starter-pack-0
  annotations:
    nginx.ingress.kubernetes.io/mergeable-ingresses: "true"
    allow-duplicate-host: "true"
    allowed-duplicate-ns: "starter-pack-0,starter-pack-1"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    external-dns.alpha.kubernetes.io/set-identifier: helloworld-blue
spec:
  rules:
  - host: helloworld.cp-2402-0759.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: helloworld-blue
            port:
              number: 80
EOF
ingress.networking.k8s.io/helloworld-blue configured
```

**_Fail case_** green ingress:
```
→ kubectl apply -f - <<EOF
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-green
  namespace: starter-pack-1
  annotations:
    nginx.ingress.kubernetes.io/mergeable-ingresses: "true"
    allow-duplicate-host: "true"
    allowed-duplicate-ns: "starter-pack-0,starter-pack-1"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    external-dns.alpha.kubernetes.io/set-identifier: helloworld-green
spec:
  rules:
  - host: helloworld.cp-2402-0759.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: helloworld-green
            port:
              number: 80
EOF
for: "STDIN": error when patching "STDIN": admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "helloworld.cp-2402-0759.cloud-platform.service.justice.gov.uk" and path "/" is already defined in ingress starter-pack-0/helloworld-blue
```

We need to add below annotation for blue green deployment with the same host and same path.

```
nginx.ingress.kubernetes.io/canary: "true"

# Defines the traffic weight for the canary.
nginx.ingress.kubernetes.io/canary-weight: "50"
```


**_Success case_** blue ingress
```
→ kubectl apply -f - <<EOF
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-blue
  namespace: starter-pack-0
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "50"
    allow-duplicate-host: "true"
    allowed-duplicate-ns: "starter-pack-0,starter-pack-1"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    external-dns.alpha.kubernetes.io/set-identifier: helloworld-blue
spec:
  rules:
  - host: helloworld.cp-2402-0759.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: helloworld-blue
            port:
              number: 4567
EOF
ingress.networking.k8s.io/helloworld-blue created
```

**_Success case_** green ingress
```
→ kubectl apply -f - <<EOF
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-green
  namespace: starter-pack-1
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "50"
    allow-duplicate-host: "true"
    allowed-duplicate-ns: "starter-pack-0,starter-pack-1"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    external-dns.alpha.kubernetes.io/set-identifier: helloworld-green
spec:
  rules:
  - host: helloworld.cp-2402-0759.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: helloworld-green
            port:
              number: 4567
EOF
ingress.networking.k8s.io/helloworld-green created
```
