### ISSUE TITLE
Catch ingress error: Unexpected error validating SSL certificate

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#6827]
relates to ministryofjustice/cloud-platform#6046

## Background

The ingress controller log error `Unexpected error validating SSL certificate` generally occurs when there is some kind of mismatch in the config between `ingress` hostname and their associated `certifcate` resource for custom domain based hostnames.

For example you would see this error firing if you had a custom domain hostname:

`my-amazing-app.content.service.justice.gov.uk`

your `cert` resource might look like:

```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: amazing-app-cert
  namespace: amazing-app
spec:
  secretName: amazing-app-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - my-amazing-app.content.service.justice.gov.uk
```

but your `ingress` config might  contain an error:

```
spec:
  ingressClassName: default
  rules:
  - host: my-amazing-app-dev.content.service.justice.gov.uk
    http:
      paths:
      - backend:
          service:
            name: my-amazing-app-service
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - my-amazing-app-dev.content.service.justice.gov.uk
    secretName: amazing-app-cert
```

We should look into seeing whether we can check for a mismatch between cert and ingress hostname values to prevent invalid ingresses being deployed with bad certs.

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
