### ISSUE TITLE
Alertmanager route for hmpps-personal-relationships-api

### ISSUE THREAD

**Issue by prabash-moj** [ministryofjustice/cloud-platform#6910]
## Service name

hmpps-personal-relationships-api

## Service environment

 [✔ ] Dev / Development
 [ ] Staging
 [✔ ] Prod / Production
 [ ✔] Other

## Impact on the service

We have renamed `hmpps-contacts-api` to `hmpps-personal-relationships-api`, We would like to reflect this name change across alerts produed by the new namespace / application
 

## Problem description

We are receiving the following alert into our `dps_alerts_non_prod` slack channel, which is produced by the personal-relationships-api application. 
As we have recently renamed this application/namespaces, etc as a result of that change, now the alert contains invalid information, which is misleading.

**See below the sample alert** 

```
[FIRING:3] :question: 5xxErrorResponses
Alert: Ingress hmpps-contacts-preprod/hmpps-contacts-api-v1-2 is serving 5xx responses.
     Details:
      - alertname: 5xxErrorResponses
      - clusterName: live
      - exported_namespace: **hmpps-contacts-preprod**
      - ingress: **hmpps-contacts-api-v1-2**
      - prometheus: monitoring/prometheus-operator-kube-p-prometheus
      - severity: digital-prison-service-dev
```

**To resolve the issue highlighted in the above alert -**
We are not 100% sure but we think the following actions would need to be applied. Appreciate your advice on this. 

1. Would we be able to rename the following custom severity level names please:

**dev:**

hmpps-contacts-data-dev - hmpps-personal-relationships-data-dev

**non-prod:**

hmpps-contacts-data-non-prod -> hmpps-personal-relationships-data-non-prod

**prod**

hmmps-contacts-data-prod -> hmpps-personal-relationships-data-prod

## Contact person

prabash.balasuriya@digital.justice.gov.uk
[Prabash Balasuriya](https://moj.enterprise.slack.com/team/U07AY7RF8AZ)
