### ISSUE TITLE
Egress Network Policy not being applied

### ISSUE THREAD

**Issue by timpeat** [ministryofjustice/cloud-platform#7295]
## Service name

LAA Crime Apply & Review

## Service environment

- [ ] Dev / Development
- [x] Staging
- [x] Prod / Production
- [ ] Other

## Impact on the service

We are unable to reduce identified risks by restricting egress to the pubic internet from our service.

## Problem description

The configured Egress NetworkPolicy is not being applied. 

Here we use `laa-criminal-applications-datastore-staging` as an example.

The Egress on this namespace is configured as follows:

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: block-egress
  namespace: laa-criminal-applications-datastore-staging
spec:
  podSelector: {}
  policyTypes:
  - Egress
```

This configuration is described correctly as shown here:

```
kubectl describe networkpolicy block-egress -n laa-criminal-applications-datastore-staging
Name:         block-egress
Namespace:    laa-criminal-applications-datastore-staging
Created on:   2025-06-25 15:00:06 +0100 BST
Labels:       <none>
Annotations:  <none>
Spec:
  PodSelector:     <none> (Allowing the specific traffic to all pods in this namespace)
  Not affecting ingress traffic
  Allowing egress traffic:
    <none> (Selected pods are isolated for egress connectivity)
  Policy Types: Egress
```

However when testing from the POD we are able freely access the public internet.

## Contact person

Please use the `#laa-crime-apply-devs` slack channel or DM `@Hibo`, `@Tim Peat`, and `@Edwin Kruglov`
